HackathonWithMVC/HackathonWithMVC/Models/Course.cs
using System.ComponentModel.DataAnnotations;

namespace HackathonWithMVC.Models
{
    public class Course
    {
        
        public int Id { get; set; }
        public string CourseName { get; set; }
        public string Author { get; set; }
        public string Category { get; set; }
        public int Price { get; set; }
        public float Rating { get; set; }
        public string ImgPath { get; set; }
    }
}

HackathonWithMVC/HackathonWithMVC/Controllers/CourseController.cs
using HackathonWithMVC.Models;
using HackathonWithMVC.Services;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace HackathonWithMVC.Controllers
{
    public class CourseController : Controller
    {
        readonly ICourseService _courseService;
        public CourseController(ICourseService courseService)
        {
            _courseService = courseService;
        }

        public ActionResult GetAllCourses()
        {
            List<Course> courses = _courseService.GetAllCourses();
            return View(courses);
        }

        public ActionResult GetCoursesByCategory(int id)
        {
            List<Course> courses = _courseService.GetCoursesByCategory(id);
            return View(courses);
        }

        public ActionResult AddToCart(int id)
        {
            User user = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("Id"));
            if (_courseService.AddToCart(id,user))
            {   
                TempData["CourseAddInfo"] = "Course Added To Cart Successfully";
                return RedirectToAction("GetAllCourses");
            }
            else
            {
                TempData["CourseAddAlert"] = "Course Already Exists OR Course Is Already Billed";
                return RedirectToAction("GetAllCourses");

            }
        }

        public ActionResult CourseDetails(int id)
        {
            Course course = _courseService.CourseDetails(id);
            return View(course);
        }

        public ActionResult ShowCart()
        {
            User user = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("Id"));
            List<Cart> carts = _courseService.ShowCart(user.Id);
            if(carts.Count>0)
            {
            return View(carts);

            }
            else
            {
                TempData["CartEmptyAlert"] = "Cart Is Empty";
                return RedirectToAction("GetAllCourses");
            }
        }

        public ActionResult RemoveFromCart(int id)
        {
            User user = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("Id"));
            _courseService.RemoveFromCart(id,user);
            TempData["CourseRemovedInfo"] = "Course Removed From Cart";
            return RedirectToAction("ShowCart");
        }

        public ActionResult BuyCourse(int id)
        {
            User user = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("Id"));
            Course course = _courseService.BuyCourse(id);
            if (_courseService.IsBilled(id, user))
            {
                TempData["CourseBilledAlert"] = "Course Is Already Billed";
                return RedirectToAction("GetAllCourses");
            }
            else
            {
                return View(course);
            }
        }

        public ActionResult GenerateBill()
        {
            User user = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("Id"));
            List<Cart> carts = _courseService.ShowCart(user.Id);
            return View(carts);
        }

        public ActionResult GetAllCoursesForAdmin()
        {
            List<Course> courses = _courseService.GetAllCourses();
            return View(courses);
        }

        [HttpGet]
        public ActionResult AddCourseForAdmin()
        {
            ViewBag.options = new List<string>()
            {
                "Web Development", "Investing and Trading", "3D and Animation", "Fitness", "Musical Instruments"
            };
            return View();
        }
        [HttpPost]
        public ActionResult AddCourseForAdmin(Course course)
        {
            ViewBag.options = new List<string>()
            {
                "Web Development", "Investing and Trading", "3D and Animation", "Fitness", "Musical Instruments"
            };

            if (_courseService.AddCourseForAdmin(course))
            {
                TempData["AddCourseInfo"] = "Course added successfully.";
                return RedirectToAction("GetAllCoursesForAdmin");

            }
            else
            {
                TempData["AddCourseInfo"] = "Course already exists.";
                return RedirectToAction("AddCourseForAdmin");
            }
            return RedirectToAction("AddCourseForAdmin");
        }


        [HttpGet]
        public ActionResult EditCourseForAdmin(int id)
        {
            ViewBag.options = new List<string>()
            {
                "Web Development", "Investing and Trading", "3D and Animation", "Fitness", "Musical Instruments"
            };
            Course course = _courseService.GetCourseById(id);
            return View(course);
        }
        [HttpPost]
        public ActionResult EditCourseForAdmin(int id, Course course)
        {
            ViewBag.options = new List<string>()
            {
                "Web Development", "Investing and Trading", "3D and Animation", "Fitness", "Musical Instruments"
            };
            _courseService.UpdateCourse(id, course);
            return RedirectToAction("GetAllCoursesForAdmin");
        }

        public ActionResult DeleteCourse(int id)
        {
            Course courseNew = _courseService.GetCourseById(id);
            _courseService.DeleteCourseDetails(courseNew);
            TempData["CourseDelInfo"] = "Course Deleted Successfully.";
            return RedirectToAction("GetAllCoursesForAdmin");
        }

        public ActionResult PayBill()
        {
            User user = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("Id"));
            List<Cart> carts = _courseService.ShowCart(user.Id);
            _courseService.Pay(user.Id);
            return View(carts);
        }

        public ActionResult BuyBill(int id)
        {
            User user = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("Id"));
            Cart cartExist = _courseService.BuyBill(id,user);
            if (cartExist != null)
            {
                return View(cartExist);
            }
            else
            {
                TempData["CourseBuyAlert"] = "Course Is Already Billed";
                return RedirectToAction("GetAllCourses");

            }

        }

        public ActionResult Orders()
        {
            User user = JsonSerializer.Deserialize<User>(HttpContext.Session.GetString("Id"));
            List<Cart> carts = _courseService.Orders(user.Id);
            if (carts.Count > 0)
            {
                return View(carts);

            }
            else
            {
                TempData["OrdersAlert"] = "No Previous Orders";
                return RedirectToAction("GetAllCourses");
            }
        }
       

        //public IActionResult Index()
        //{
        //    return View();
        //}
    }
}

HackathonWithMVC/HackathonWithMVC/Views/Course/AddCourseForAdmin.cshtml
@model HackathonWithMVC.Models.Course

@{
    ViewData["Title"] = "AddCourseForAdmin";
    Layout = "~/Views/Shared/_NavAdmin.cshtml";
}


<h1 class="text-center">Add New Course</h1>

@{
    if (TempData["AddCourseInfo"] != null)
    {

        <div class="alert alert-danger" role="alert">
            @TempData["AddCourseInfo"]
        </div>
    }
    TempData["AddCourseInfo"] = null;
}
<hr />
<div class="row">
    <div class="col-md-4 addCourse text-center">
        <form asp-action="AddCourseForAdmin" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="CourseName" placeholder="Coursename" class="form-control text-center" />
                <span asp-validation-for="CourseName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input asp-for="Author" placeholder="Author" class="form-control text-center" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <select asp-for="Category" placeholder="Category" class="form-control text-center">
                    @foreach (string item in ViewBag.options)
                    {
                        <option value=@item>@item</option>
                    }
                </select>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input asp-for="ImgPath" placeholder="Image Path" class="form-control text-center" />
                <span asp-validation-for="ImgPath" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input asp-for="Price" placeholder="Price" class="form-control text-center" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input asp-for="Rating" placeholder="Rating" class="form-control text-center" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Add Course" class="btn btn-primary" />
                <a class="btn btn-primary" asp-action="GetAllCoursesForAdmin">Back To Course List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

HackathonWithMVC/HackathonWithMVC/Views/Course/AddToCart.cshtml
@model IEnumerable<HackathonWithMVC.Models.Course>

@{
    ViewData["Title"] = "AddToCart";
    Layout = "~/Views/Shared/_NavUser.cshtml";
}

<h1>AddToCart</h1>

<p>
    <a asp-action="">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CourseName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

HackathonWithMVC/HackathonWithMVC/Views/Course/BuyBill.cshtml
@model HackathonWithMVC.Models.Cart

@{
    ViewData["Title"] = "BuyBill";
    Layout = "~/Views/Shared/_NavUser.cshtml";
    float total = @Model.Price;
}

<h1 class="text-center">Your Bill</h1>
<h2>Thank You @TempData["Username"]!! <br />
    Your Payment Of Rs. @(total * 0.18 + total) Was Successful</h2>
    @{
        TempData.Keep("Username");
    }
<div>
    
    <hr />
    <dl class="row">
        <dd class = "col-sm-10">
            <img src="@Model.ImgPath" style="width: 250px"/>
        </dd>
        <dt  class = "col-sm-2"></dt>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CourseName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>        
    </dl>
</div>
<div>
    <a class="btn btn-sm btn-primary" asp-action="GetAllCourses">Back to List</a>
</div>

HackathonWithMVC/HackathonWithMVC/Views/Course/BuyCourse.cshtml
@model HackathonWithMVC.Models.Course

@{
    ViewData["Title"] = "BuyCourse";
    Layout = "~/Views/Shared/_NavUser.cshtml";
}

<h1 class="text-center">Buy Course</h1>

<div>
    <hr />
    <dl class="row">
        <dd class = "col-sm-10">
            <img src="@Model.ImgPath" style="width: 250px"/>
        </dd>
        <dt  class = "col-sm-2"></dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CourseName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        @{
            double priceWithGST = (float)(@Model.Price * 0.18) + @Model.Price;
        }
    </dl>
    <hr />
    <h2>Price: @Model.Price</h2>
    <h2>Price Payable with GST: @priceWithGST</h2>
</div>
<div>
    <a class="btn btn-sm btn-primary" asp-action="GetAllCourses">Back To Courses</a>
    <a class="btn btn-sm btn-primary" asp-action="BuyBill" asp-route-id="@Model.Id">Proceed To Pay</a>
    
</div>

HackathonWithMVC/HackathonWithMVC/Views/Course/CourseDetails.cshtml
@model HackathonWithMVC.Models.Course

@{
    ViewData["Title"] = "CourseDetails";
    Layout = "~/Views/Shared/_NavUser.cshtml";
}

<h1 class="text-center">Course Details</h1>

<div>
    <h4>@Model.CourseName</h4>
    <div>
    <a class="btn btn-primary btn-sm" asp-action="AddToCart" asp-route-id="@Model?.Id">Add To Cart</a> 
    <a class="btn btn-primary btn-sm" asp-action="BuyCourse" asp-route-id="@Model?.Id">Buy Course</a> 
    <a class="btn btn-primary btn-sm" asp-action="GetAllCourses">Back To Courses</a>
</div>
    <hr />
    <dl class="row">
        <dd class = "col-sm-10">
            <img src="@Model.ImgPath" style="width: 250px"/>
        </dd>
        <dt  class = "col-sm-2"></dt>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CourseName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
</div>

HackathonWithMVC/HackathonWithMVC/Views/Course/EditCourseForAdmin.cshtml
@model HackathonWithMVC.Models.Course

@{
    ViewData["Title"] = "EditCourseForAdmin";
    Layout = "~/Views/Shared/_NavAdmin.cshtml";
}


<h1 class="text-center">Edit Course</h1>

<hr />
<div class="row">
    <div class="col-md-4 editCourse text-center">
        <form asp-action="EditCourseForAdmin" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CourseName" class="control-label"></label>
                <input asp-for="CourseName" class="form-control text-center" />
                <span asp-validation-for="CourseName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control text-center" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="Category" class="form-control text-center">
                    @foreach (string item in ViewBag.options)
                    {
                        <option value=@item>@item</option>
                    }
                </select>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="ImgPath" class="control-label"></label>
                <input asp-for="ImgPath" class="form-control text-center" />
                <span asp-validation-for="ImgPath" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control text-center" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control text-center" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Make Changes" class="btn btn-primary" />
                <a class="btn btn-primary" asp-action="GetAllCoursesForAdmin">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

HackathonWithMVC/HackathonWithMVC/Views/Course/GenerateBill.cshtml
@model IEnumerable<HackathonWithMVC.Models.Cart>

@{
    ViewData["Title"] = "GenerateBill";
    Layout = "~/Views/Shared/_NavUser.cshtml";
    float total = 0;
    int count = 1;

}

<h1 class="text-center">Your Bill</h1>
<hr />
@foreach (var item in Model)
{
    total += @item.Price;
}
<h2>Price Payable with GST: Rs. @(total * 0.18 + total)</h2>
<h3>Date: @DateTime.Now</h3>
<h3>For @TempData["Username"]</h3>
@{
    TempData.Keep("Username");
}

<p>
    <a class="btn btn-primary btn-sm" asp-action="ShowCart">Back To Cart</a>
    <a class="btn btn-primary btn-sm" asp-action="PayBill" asp-controller="Course">Proceed To Pay</a>
</p>
<table class="table text-center">
    <thead>
        <tr>
            <th></th>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.CourseName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="align-middle">
                <td>@count</td>
                <td>
                    <img src="@item.ImgPath" style="width: 150px">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <a asp-action="CourseDetails" asp-route-id="@item.CourseId">Details</a>
                </td>
            </tr>
            count++;

        }
    </tbody>
    <tfoot>
    <td></td>
    <td></td>
    <td></td>
    <td>Rs. @total</td>
    <td></td>
    </tfoot>
</table>

HackathonWithMVC/HackathonWithMVC/Views/Course/GetAllCourses.cshtml
@model IEnumerable<HackathonWithMVC.Models.Course>

@{
    ViewData["Title"] = "GetAllCourses";
    Layout = "~/Views/Shared/_NavUser.cshtml";
}

<h1 class="text-center">Courses</h1>
@{
    if (TempData["CourseAddInfo"] != null)
    {

        <div class="alert alert-success" role="alert">
            @TempData["CourseAddInfo"]
        </div>
    }else if (TempData["CourseAddAlert"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["CourseAddAlert"]
        </div>
    }

    if(TempData["CartEmptyAlert"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["CartEmptyAlert"]
        </div>
    }

    if(TempData["CourseBilledAlert"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["CourseBilledAlert"]
        </div>
    }
    
    if(TempData["CourseBuyAlert"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["CourseBuyAlert"]
        </div>
    }
    
    if(TempData["OrdersAlert"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["OrdersAlert"]
        </div>
    }
}
<hr />
<h2>Welcome @TempData["Username"]</h2>
@{
    TempData.Keep("Username");
}
<p>
    <a class="btn btn-primary" asp-action="GetCoursesByCategory">Courses By Category</a>
</p>
<table class="table text-center">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.CourseName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="align-middle">
                <td>
                    <img src="@item.ImgPath" style="width: 150px">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    <a class="btn m-1 btn-success btn-sm" asp-action="AddToCart" asp-route-id="@item.Id">Add To Cart</a> <br>
                    <a class="btn m-1 btn-primary text-light btn-sm" asp-action="CourseDetails" asp-route-id="@item.Id">Details</a> <br> 
                    <a class="btn m-1 btn-success btn-sm" asp-action="BuyCourse" asp-route-id="@item.Id">Buy Course</a>
                </td>
            </tr>
        }
    </tbody>
</table>

HackathonWithMVC/HackathonWithMVC/Views/Course/GetAllCoursesForAdmin.cshtml
@model IEnumerable<HackathonWithMVC.Models.Course>

@{
    ViewData["Title"] = "GetAllCoursesForAdmin";
    Layout = "~/Views/Shared/_NavAdmin.cshtml";
}


<h1 class="text-center">All Courses</h1>
<hr />
@{
    if (TempData["AddCourseInfo"] != null)
    {

        <div class="alert alert-primary" role="alert">
            @TempData["AddCourseInfo"]
        </div>
    }
    TempData["AddCourseInfo"] = null;

    if (TempData["CourseDelInfo"] != null)
    {

        <div class="alert alert-danger" role="alert">
            @TempData["CourseDelInfo"]
        </div>
    }
    TempData["CourseDelInfo"] = null;
}

<p>
    <a class="btn btn-sm btn-primary" asp-action="AddCourseForAdmin">Add New Course</a>
</p>
<table class="table text-center">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.CourseName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="align-middle">
                <td>
                    <img src="@item.ImgPath" style="width: 150px">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    <a class="btn m-1 btn-sm btn-primary" asp-action="EditCourseForAdmin" asp-route-id="@item.Id">Edit</a>
                    <br/>
                    <a class="btn m-1 btn-sm btn-primary" asp-action="DeleteCourse" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

HackathonWithMVC/HackathonWithMVC/Views/Course/GetCoursesByCategory.cshtml
@model IEnumerable<HackathonWithMVC.Models.Course>

@{
    ViewData["Title"] = "GetCoursesByCategory";
    Layout = "~/Views/Shared/_NavUser.cshtml";
}

<h1 class="text-center">Courses</h1>
@{
    if (TempData["CourseAddInfo"] != null)
    {

        <div class="alert alert-danger" role="alert">
            @TempData["CourseAddInfo"]
        </div>
    }TempData["CourseAddInfo"] = null;
}

<hr />
<h2 class="text-center">Select Courses By Category:</h2>

<p class="text-center">
    <a class="btn btn-sm btn-primary" asp-action="GetCoursesByCategory" asp-route-id="1">Web Development</a>
    <a class="btn btn-sm btn-primary"  asp-action="GetCoursesByCategory" asp-route-id="2">Investing and Trading</a>
    <a class="btn btn-sm btn-primary"  asp-action="GetCoursesByCategory" asp-route-id="3">3D and Animation</a>
    <a class="btn btn-sm btn-primary"  asp-action="GetCoursesByCategory" asp-route-id="4">Fitness</a>
    <a class="btn btn-sm btn-primary"  asp-action="GetCoursesByCategory" asp-route-id="5">Musical Instruments</a>
</p>
<table class="table text-center">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.CourseName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="align-middle">
                <td>
                    <img src="@item.ImgPath" style="width: 150px">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    <a class="btn m-1 btn-success btn-sm" asp-action="AddToCart" asp-route-id="@item.Id">Add To Cart</a> <br>
                    <a class="btn m-1 btn-primary text-light btn-sm" asp-action="CourseDetails" asp-route-id="@item.Id">Details</a> <br> 
                    <a class="btn m-1 btn-success btn-sm" asp-action="BuyCourse" asp-route-id="@item.Id">Buy Course</a>
                </td>
            </tr>
        }
    </tbody>
</table>